file=open(r"C:\Users\shubh\Desktop\LnB_assignments\Assignments 3\lnbfile.txt","w+")
qw=input("Enter text to add to the file:- ")
file.write(qw)
data=file.read()
data=data.lower()
co=data.count("to")
print("Number of time 'to' appeared:- ",co)
cd=data.count("the")
print("Number of times 'the' appeard",cd)